# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import re
import shutil
import sys
from typing import Any, Dict, List, Optional

from docutils import nodes
from sphinx.application import Sphinx

basedir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "src"))
sys.path.insert(0, basedir)
import majorana_karaoke

ALLOWED_SPECIAL_METHODS = ["__init__", "__call__"]
GITHUB_MATH_FENCE = re.compile(
    r"^(?P<indent>[ \t]*)```math[ \t]*\n(?P<body>.*?)\n(?P=indent)```[ \t]*$", re.DOTALL | re.MULTILINE
)
GITHUB_INLINE_MATH = re.compile(r"\$`([^`\n]+?)`\$")

_html_folders_formatted: Dict[str, str] = {}


def skip(app: Sphinx, what: str, name: str, obj: Any, would_skip: bool, options: Any) -> bool:
    """
    Document the special methods listed in ``ALLOWED_SPECIAL_METHODS``, which autodoc skips by default.

    :param app: The Sphinx application.
    :type app: Sphinx
    :param what: The type of the object the member belongs to.
    :type what: str
    :param name: The name of the member.
    :type name: str
    :param obj: The member itself.
    :type obj: Any
    :param would_skip: Whether autodoc would skip the member.
    :type would_skip: bool
    :param options: The options given to the autodoc directive.
    :type options: Any
    :return: False to document the member, ``would_skip`` otherwise.
    :rtype: bool
    """
    if name in ALLOWED_SPECIAL_METHODS:
        return False
    return would_skip


def github_math_to_myst(app: Sphinx, docname: str, source: List[str]) -> None:
    """
    Rewrite GitHub-flavored math delimiters to MyST dollarmath before parsing.

    The ``README.md`` uses GitHub-flavored math so that it renders on github.com: inline math is wrapped in
    ``$`...`$`` and display math in ```` ```math ```` fences, both of which keep the LaTeX literal and protect it from
    GitHub's markdown sanitizer. MyST's dollarmath expects ``$...$`` and ``$$...$$`` instead, so this handler converts
    the GitHub forms in place when Sphinx reads each source. A fence indented inside a list item keeps its
    indentation, and blank lines are put around every display block because a ``$$`` block, unlike a fence, cannot
    interrupt a paragraph.

    The handler only sees documents, not the files they include, which is why ``readme.md`` is a symbolic link to the
    ``README.md`` rather than an ``include`` directive.

    :param app: The Sphinx application.
    :type app: Sphinx
    :param docname: The name of the document being read.
    :type docname: str
    :param source: A list whose single item is the source of the document, modified in place.
    :type source: List[str]
    :return: None
    :rtype: None
    """
    text = source[0]
    text = GITHUB_MATH_FENCE.sub(
        lambda match: f"\n{match.group('indent')}$$\n{match.group('body')}\n{match.group('indent')}$$\n", text
    )
    text = GITHUB_INLINE_MATH.sub(lambda match: "$" + match.group(1) + "$", text)
    source[0] = text


def drop_mathjax3_config(app: Sphinx) -> None:
    """
    Drop the MathJax configuration generated by ``myst_parser``, which this theme cannot render.

    ``myst_parser`` fills ``mathjax3_config`` so that MathJax only looks at the elements it marked, which makes
    ``sphinx.ext.mathjax`` ship that configuration as a script asset carrying a body instead of a file name. The
    ``karma_sphinx_theme`` layout renders every script asset as ``<script src="...">`` and ignores the body, so the
    asset becomes a link to a file named ``None`` that answers 404 on every page carrying it. ``_templates/layout.html``
    already writes the same ``window.MathJax`` object by hand, so nothing is lost by dropping the generated one. The
    handler is connected with a priority above the default that ``myst_parser`` registers with, so it always runs after
    the value ``myst_parser`` sets.

    :param app: The Sphinx application.
    :type app: Sphinx
    :return: None
    :rtype: None
    """
    app.config.mathjax3_config = None


def change_pathto(
    app: Sphinx,
    pagename: str,
    templatename: str,
    context: Dict[str, Any],
    doctree: Optional[nodes.document],
) -> None:
    """
    Replace the ``pathto`` helper of the templates so that it drops the leading underscore of folder names.

    GitHub Pages does not serve folders whose name starts with an underscore, such as ``_static``, unless the site
    has a ``.nojekyll`` file. The folders are renamed by :func:`move_private_folders` once the build is finished.

    :param app: The Sphinx application.
    :type app: Sphinx
    :param pagename: The name of the page being rendered.
    :type pagename: str
    :param templatename: The name of the template rendering the page.
    :type templatename: str
    :param context: The context of the template, modified in place.
    :type context: Dict[str, Any]
    :param doctree: The doctree of the page, if it has one.
    :type doctree: Optional[nodes.document]
    :return: None
    :rtype: None
    """
    pathto = context.get("pathto")

    def gh_pathto(otheruri: str, *args: Any, **kwargs: Any) -> str:
        if otheruri.startswith("_"):
            otheruri_formatted = otheruri[1:]
            _html_folders_formatted[os.path.dirname(otheruri)] = os.path.dirname(otheruri_formatted)
        else:
            otheruri_formatted = otheruri
        return pathto(otheruri_formatted, *args, **kwargs)

    context["pathto"] = gh_pathto


def move_private_folders(app: Sphinx, exception: Optional[Exception]) -> None:
    """
    Remove the leading underscore of the folders of the output that :func:`change_pathto` renamed in the links.

    A folder left by a previous build into the same output directory is replaced, so that a rebuild does not nest
    the new folder inside the old one.

    :param app: The Sphinx application.
    :type app: Sphinx
    :param exception: The exception that stopped the build, if any.
    :type exception: Optional[Exception]
    :return: None
    :rtype: None
    """

    def join(folder_name: str) -> str:
        return os.path.join(app.builder.outdir, folder_name)

    for item in os.listdir(app.builder.outdir):
        if item.startswith("_") and os.path.isdir(join(item)) and item in _html_folders_formatted:
            if os.path.isdir(join(item[1:])):
                shutil.rmtree(join(item[1:]))
            shutil.move(join(item), join(item[1:]))


def setup(app: Sphinx) -> None:
    """
    Connect the handlers of this file to the events of Sphinx.

    :param app: The Sphinx application.
    :type app: Sphinx
    :return: None
    :rtype: None
    """
    # sphinx.ext.mathjax only loads MathJax on a page whose own document holds math, so a page that merely quotes a
    # math-bearing section title in a toctree would show the LaTeX source of that title instead of the formula.
    app.set_html_assets_policy("always")
    app.connect("builder-inited", drop_mathjax3_config, priority=800)
    app.connect("source-read", github_math_to_myst)
    app.connect("autodoc-skip-member", skip)
    app.connect("html-page-context", change_pathto)
    app.connect("build-finished", move_private_folders)


# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "MajoranaKaraoke"
copyright = majorana_karaoke.__copyright__.replace("Copyright ", "")
author = majorana_karaoke.__author__
version = majorana_karaoke.__version__
release = majorana_karaoke.__version__

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.githubpages",
    "myst_nb",
    "sphinx.ext.mathjax",
]

nb_execution_mode = "off"

myst_enable_extensions = ["dollarmath", "colon_fence"]

templates_path = ["_templates"]
exclude_patterns = ["tutorials/README.md"]

suppress_warnings = ["myst.header"]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "karma_sphinx_theme"
html_theme_options = {"navigation_depth": 2}
html_static_path = ["_static"]
mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
